name: My-First-Work-Flow
on: 
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Test:
    name: Build and Print
    runs-on: ubuntu-22.04
    steps:
      - name: Print the name
        run: echo "My name is maximus decimus meridius"
      - name: run series of commands
        run: |
          echo " #1 Line"
          echo " #2 line"
          echo " # third line"
      - name: checout repository
        uses: actions/checkout@v4

      - name: Run Script
        run: |
          ls
          echo "print hideen files"
          ls -la
          echo "check storage"
          df -h
          
  
    
